image: "vmaksimenko/mongo-node"

stages: 
  - test
  - deploy

run_test: 
  stage: test
  script:
    - npm run dev:install
    - npm run cy:verify
    # - npm run mongo:start
    - npm run mongo:restore:local
    - nohup npm run dev:run &
    - npm run e2e_mochawesome

