image: node:4.4.0

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

services:
  - mongo

variables:
  MONGODB_URI: 'mongodb://mongo/conduit'
  NODE_ENV: 'production'

run_test: 
  script:
    - npm run dev:install
    - npm run cy:verify
    # - npm run mongo:start
    - ps -aux | grep 21017
    # - npm run mongo:restore:local
    - nohup npm run dev:run &
    - npm run wait-for-server
    - npm run e2e_mochawesome

