language: node_js
node_js: "11.8.0"

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm run dev:install
    - npm run cy:verify

sudo: required
services: mongodb

before_install:
  - npm run dev:install
  - npm run cy:verify
  # - npm run mongo:start
  - npm run mongo:restore:local

script: 
  - nohup npm run dev:run &
  - npm run wait-for-server
  - npm run e2e_mochawesome
